name: Lint & Test

on:
  push: 
  pull_request:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  lint-and-test:
    name: Lint & Test
    runs-on: self-hosted
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Install dependencies
        run: |
          pnpm install

      - name: Lint
        run: pnpm exec turbo lint
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

      - name: Typecheck
        run: pnpm exec turbo typecheck
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

      - name: Build
        run: pnpm exec turbo build
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

      - name: Check format
        run: pnpm exec turbo format:check
        env:
          TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}

